basePath: /
definitions:
  models.Book:
    properties:
      author:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.Health:
    properties:
      status:
        type: string
      timestamp:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing your reading list
  title: Want to Read API
  version: "1.0"
paths:
  /book:
    post:
      description: Add a book into the database
      parameters:
      - description: Book to add
        in: body
        name: book
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add book
      tags:
      - books
  /books:
    get:
      description: Get a list of all books in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List all books
      tags:
      - books
  /health:
    get:
      description: Get the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Health'
      summary: Health check endpoint
      tags:
      - health
swagger: "2.0"
